# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from app.valhalla_proto import options_pb2 as options__pb2
try:
  common__pb2 = options__pb2.common__pb2
except AttributeError:
  common__pb2 = options__pb2.common_pb2
from app.valhalla_proto import trip_pb2 as trip__pb2
try:
  common__pb2 = trip__pb2.common__pb2
except AttributeError:
  common__pb2 = trip__pb2.common_pb2
try:
  sign__pb2 = trip__pb2.sign__pb2
except AttributeError:
  sign__pb2 = trip__pb2.sign_pb2
try:
  common__pb2 = trip__pb2.common__pb2
except AttributeError:
  common__pb2 = trip__pb2.common_pb2
from app.valhalla_proto import directions_pb2 as directions__pb2
try:
  common__pb2 = directions__pb2.common__pb2
except AttributeError:
  common__pb2 = directions__pb2.common_pb2
try:
  sign__pb2 = directions__pb2.sign__pb2
except AttributeError:
  sign__pb2 = directions__pb2.sign_pb2
try:
  common__pb2 = directions__pb2.common__pb2
except AttributeError:
  common__pb2 = directions__pb2.common_pb2
from app.valhalla_proto import info_pb2 as info__pb2
from app.valhalla_proto import status_pb2 as status__pb2

from app.valhalla_proto.options_pb2 import *
from app.valhalla_proto.trip_pb2 import *
from app.valhalla_proto.directions_pb2 import *
from app.valhalla_proto.info_pb2 import *
from app.valhalla_proto.status_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='api.proto',
  package='valhalla',
  syntax='proto3',
  serialized_options=b'H\003',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\tapi.proto\x12\x08valhalla\x1a\roptions.proto\x1a\ntrip.proto\x1a\x10\x64irections.proto\x1a\ninfo.proto\x1a\x0cstatus.proto\"\xb1\x01\n\x03\x41pi\x12\"\n\x07options\x18\x01 \x01(\x0b\x32\x11.valhalla.Options\x12\x1c\n\x04trip\x18\x02 \x01(\x0b\x32\x0e.valhalla.Trip\x12(\n\ndirections\x18\x03 \x01(\x0b\x32\x14.valhalla.Directions\x12 \n\x06status\x18\x04 \x01(\x0b\x32\x10.valhalla.Status\x12\x1c\n\x04info\x18\x14 \x01(\x0b\x32\x0e.valhalla.InfoB\x02H\x03P\x00P\x01P\x02P\x03P\x04\x62\x06proto3'
  ,
  dependencies=[options__pb2.DESCRIPTOR,trip__pb2.DESCRIPTOR,directions__pb2.DESCRIPTOR,info__pb2.DESCRIPTOR,status__pb2.DESCRIPTOR,],
  public_dependencies=[options__pb2.DESCRIPTOR,trip__pb2.DESCRIPTOR,directions__pb2.DESCRIPTOR,info__pb2.DESCRIPTOR,status__pb2.DESCRIPTOR,])




_API = _descriptor.Descriptor(
  name='Api',
  full_name='valhalla.Api',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='options', full_name='valhalla.Api.options', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='trip', full_name='valhalla.Api.trip', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='directions', full_name='valhalla.Api.directions', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='valhalla.Api.status', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='info', full_name='valhalla.Api.info', index=4,
      number=20, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=272,
)

_API.fields_by_name['options'].message_type = options__pb2._OPTIONS
_API.fields_by_name['trip'].message_type = trip__pb2._TRIP
_API.fields_by_name['directions'].message_type = directions__pb2._DIRECTIONS
_API.fields_by_name['status'].message_type = status__pb2._STATUS
_API.fields_by_name['info'].message_type = info__pb2._INFO
DESCRIPTOR.message_types_by_name['Api'] = _API
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Api = _reflection.GeneratedProtocolMessageType('Api', (_message.Message,), {
  'DESCRIPTOR' : _API,
  '__module__' : 'api_pb2'
  # @@protoc_insertion_point(class_scope:valhalla.Api)
  })
_sym_db.RegisterMessage(Api)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
