# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: info.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='info.proto',
  package='valhalla',
  syntax='proto3',
  serialized_options=b'H\003',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\ninfo.proto\x12\x08valhalla\"a\n\tStatistic\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01\x12\x11\n\tfrequency\x18\x03 \x01(\x02\x12%\n\x04type\x18\x04 \x01(\x0e\x32\x17.valhalla.StatisticType\"5\n\x10\x43odedDescription\x12\x13\n\x0b\x64\x65scription\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x04\"\x9d\x01\n\x04Info\x12\'\n\nstatistics\x18\x01 \x03(\x0b\x32\x13.valhalla.Statistic\x12*\n\x06\x65rrors\x18\x02 \x03(\x0b\x32\x1a.valhalla.CodedDescription\x12,\n\x08warnings\x18\x03 \x03(\x0b\x32\x1a.valhalla.CodedDescription\x12\x12\n\nis_service\x18\x04 \x01(\x08*:\n\rStatisticType\x12\t\n\x05\x63ount\x10\x00\x12\t\n\x05gauge\x10\x01\x12\n\n\x06timing\x10\x02\x12\x07\n\x03set\x10\x03\x42\x02H\x03\x62\x06proto3'
)

_STATISTICTYPE = _descriptor.EnumDescriptor(
  name='StatisticType',
  full_name='valhalla.StatisticType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='count', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='gauge', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='timing', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='set', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=338,
  serialized_end=396,
)
_sym_db.RegisterEnumDescriptor(_STATISTICTYPE)

StatisticType = enum_type_wrapper.EnumTypeWrapper(_STATISTICTYPE)
count = 0
gauge = 1
timing = 2
set = 3



_STATISTIC = _descriptor.Descriptor(
  name='Statistic',
  full_name='valhalla.Statistic',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='valhalla.Statistic.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='valhalla.Statistic.value', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='frequency', full_name='valhalla.Statistic.frequency', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='valhalla.Statistic.type', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=121,
)


_CODEDDESCRIPTION = _descriptor.Descriptor(
  name='CodedDescription',
  full_name='valhalla.CodedDescription',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='description', full_name='valhalla.CodedDescription.description', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='code', full_name='valhalla.CodedDescription.code', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=123,
  serialized_end=176,
)


_INFO = _descriptor.Descriptor(
  name='Info',
  full_name='valhalla.Info',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='statistics', full_name='valhalla.Info.statistics', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='errors', full_name='valhalla.Info.errors', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='warnings', full_name='valhalla.Info.warnings', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_service', full_name='valhalla.Info.is_service', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=179,
  serialized_end=336,
)

_STATISTIC.fields_by_name['type'].enum_type = _STATISTICTYPE
_INFO.fields_by_name['statistics'].message_type = _STATISTIC
_INFO.fields_by_name['errors'].message_type = _CODEDDESCRIPTION
_INFO.fields_by_name['warnings'].message_type = _CODEDDESCRIPTION
DESCRIPTOR.message_types_by_name['Statistic'] = _STATISTIC
DESCRIPTOR.message_types_by_name['CodedDescription'] = _CODEDDESCRIPTION
DESCRIPTOR.message_types_by_name['Info'] = _INFO
DESCRIPTOR.enum_types_by_name['StatisticType'] = _STATISTICTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Statistic = _reflection.GeneratedProtocolMessageType('Statistic', (_message.Message,), {
  'DESCRIPTOR' : _STATISTIC,
  '__module__' : 'info_pb2'
  # @@protoc_insertion_point(class_scope:valhalla.Statistic)
  })
_sym_db.RegisterMessage(Statistic)

CodedDescription = _reflection.GeneratedProtocolMessageType('CodedDescription', (_message.Message,), {
  'DESCRIPTOR' : _CODEDDESCRIPTION,
  '__module__' : 'info_pb2'
  # @@protoc_insertion_point(class_scope:valhalla.CodedDescription)
  })
_sym_db.RegisterMessage(CodedDescription)

Info = _reflection.GeneratedProtocolMessageType('Info', (_message.Message,), {
  'DESCRIPTOR' : _INFO,
  '__module__' : 'info_pb2'
  # @@protoc_insertion_point(class_scope:valhalla.Info)
  })
_sym_db.RegisterMessage(Info)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
