# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sign.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from app.valhalla_proto import common_pb2 as common__pb2

from app.valhalla_proto.common_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='sign.proto',
  package='valhalla',
  syntax='proto3',
  serialized_options=b'H\003',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nsign.proto\x12\x08valhalla\x1a\x0c\x63ommon.proto\"\x83\x01\n\x0fTripSignElement\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x17\n\x0fis_route_number\x18\x02 \x01(\x08\x12\x19\n\x11\x63onsecutive_count\x18\x03 \x01(\r\x12.\n\rpronunciation\x18\x04 \x01(\x0b\x32\x17.valhalla.Pronunciation\"\xf8\x03\n\x08TripSign\x12/\n\x0c\x65xit_numbers\x18\x01 \x03(\x0b\x32\x19.valhalla.TripSignElement\x12\x34\n\x11\x65xit_onto_streets\x18\x02 \x03(\x0b\x32\x19.valhalla.TripSignElement\x12\x38\n\x15\x65xit_toward_locations\x18\x03 \x03(\x0b\x32\x19.valhalla.TripSignElement\x12-\n\nexit_names\x18\x04 \x03(\x0b\x32\x19.valhalla.TripSignElement\x12\x35\n\x12guide_onto_streets\x18\x05 \x03(\x0b\x32\x19.valhalla.TripSignElement\x12\x39\n\x16guide_toward_locations\x18\x06 \x03(\x0b\x32\x19.valhalla.TripSignElement\x12\x31\n\x0ejunction_names\x18\x07 \x03(\x0b\x32\x19.valhalla.TripSignElement\x12:\n\x17guidance_view_junctions\x18\x08 \x03(\x0b\x32\x19.valhalla.TripSignElement\x12;\n\x18guidance_view_signboards\x18\t \x03(\x0b\x32\x19.valhalla.TripSignElementB\x02H\x03P\x00\x62\x06proto3'
  ,
  dependencies=[common__pb2.DESCRIPTOR,],
  public_dependencies=[common__pb2.DESCRIPTOR,])




_TRIPSIGNELEMENT = _descriptor.Descriptor(
  name='TripSignElement',
  full_name='valhalla.TripSignElement',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='valhalla.TripSignElement.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_route_number', full_name='valhalla.TripSignElement.is_route_number', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='consecutive_count', full_name='valhalla.TripSignElement.consecutive_count', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pronunciation', full_name='valhalla.TripSignElement.pronunciation', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=170,
)


_TRIPSIGN = _descriptor.Descriptor(
  name='TripSign',
  full_name='valhalla.TripSign',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='exit_numbers', full_name='valhalla.TripSign.exit_numbers', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='exit_onto_streets', full_name='valhalla.TripSign.exit_onto_streets', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='exit_toward_locations', full_name='valhalla.TripSign.exit_toward_locations', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='exit_names', full_name='valhalla.TripSign.exit_names', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='guide_onto_streets', full_name='valhalla.TripSign.guide_onto_streets', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='guide_toward_locations', full_name='valhalla.TripSign.guide_toward_locations', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='junction_names', full_name='valhalla.TripSign.junction_names', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='guidance_view_junctions', full_name='valhalla.TripSign.guidance_view_junctions', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='guidance_view_signboards', full_name='valhalla.TripSign.guidance_view_signboards', index=8,
      number=9, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=173,
  serialized_end=677,
)

_TRIPSIGNELEMENT.fields_by_name['pronunciation'].message_type = common__pb2._PRONUNCIATION
_TRIPSIGN.fields_by_name['exit_numbers'].message_type = _TRIPSIGNELEMENT
_TRIPSIGN.fields_by_name['exit_onto_streets'].message_type = _TRIPSIGNELEMENT
_TRIPSIGN.fields_by_name['exit_toward_locations'].message_type = _TRIPSIGNELEMENT
_TRIPSIGN.fields_by_name['exit_names'].message_type = _TRIPSIGNELEMENT
_TRIPSIGN.fields_by_name['guide_onto_streets'].message_type = _TRIPSIGNELEMENT
_TRIPSIGN.fields_by_name['guide_toward_locations'].message_type = _TRIPSIGNELEMENT
_TRIPSIGN.fields_by_name['junction_names'].message_type = _TRIPSIGNELEMENT
_TRIPSIGN.fields_by_name['guidance_view_junctions'].message_type = _TRIPSIGNELEMENT
_TRIPSIGN.fields_by_name['guidance_view_signboards'].message_type = _TRIPSIGNELEMENT
DESCRIPTOR.message_types_by_name['TripSignElement'] = _TRIPSIGNELEMENT
DESCRIPTOR.message_types_by_name['TripSign'] = _TRIPSIGN
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TripSignElement = _reflection.GeneratedProtocolMessageType('TripSignElement', (_message.Message,), {
  'DESCRIPTOR' : _TRIPSIGNELEMENT,
  '__module__' : 'sign_pb2'
  # @@protoc_insertion_point(class_scope:valhalla.TripSignElement)
  })
_sym_db.RegisterMessage(TripSignElement)

TripSign = _reflection.GeneratedProtocolMessageType('TripSign', (_message.Message,), {
  'DESCRIPTOR' : _TRIPSIGN,
  '__module__' : 'sign_pb2'
  # @@protoc_insertion_point(class_scope:valhalla.TripSign)
  })
_sym_db.RegisterMessage(TripSign)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
