# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: status.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='status.proto',
  package='valhalla',
  syntax='proto3',
  serialized_options=b'H\003',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cstatus.proto\x12\x08valhalla\"\xcf\x02\n\x06Status\x12\x13\n\thas_tiles\x18\x01 \x01(\x08H\x00\x12\x14\n\nhas_admins\x18\x02 \x01(\x08H\x01\x12\x17\n\rhas_timezones\x18\x03 \x01(\x08H\x02\x12\x1a\n\x10has_live_traffic\x18\x04 \x01(\x08H\x03\x12\x0e\n\x04\x62\x62ox\x18\x05 \x01(\tH\x04\x12\x11\n\x07version\x18\x06 \x01(\tH\x05\x12\x1f\n\x15tileset_last_modified\x18\x07 \x01(\rH\x06\x12\x19\n\x11\x61vailable_actions\x18\x08 \x03(\tB\x0f\n\rhas_has_tilesB\x10\n\x0ehas_has_adminsB\x13\n\x11has_has_timezonesB\x16\n\x14has_has_live_trafficB\n\n\x08has_bboxB\r\n\x0bhas_versionB\x1b\n\x19has_tileset_last_modifiedB\x02H\x03\x62\x06proto3'
)




_STATUS = _descriptor.Descriptor(
  name='Status',
  full_name='valhalla.Status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='has_tiles', full_name='valhalla.Status.has_tiles', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='has_admins', full_name='valhalla.Status.has_admins', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='has_timezones', full_name='valhalla.Status.has_timezones', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='has_live_traffic', full_name='valhalla.Status.has_live_traffic', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bbox', full_name='valhalla.Status.bbox', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='version', full_name='valhalla.Status.version', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tileset_last_modified', full_name='valhalla.Status.tileset_last_modified', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='available_actions', full_name='valhalla.Status.available_actions', index=7,
      number=8, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='has_has_tiles', full_name='valhalla.Status.has_has_tiles',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='has_has_admins', full_name='valhalla.Status.has_has_admins',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='has_has_timezones', full_name='valhalla.Status.has_has_timezones',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='has_has_live_traffic', full_name='valhalla.Status.has_has_live_traffic',
      index=3, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='has_bbox', full_name='valhalla.Status.has_bbox',
      index=4, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='has_version', full_name='valhalla.Status.has_version',
      index=5, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='has_tileset_last_modified', full_name='valhalla.Status.has_tileset_last_modified',
      index=6, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=27,
  serialized_end=362,
)

_STATUS.oneofs_by_name['has_has_tiles'].fields.append(
  _STATUS.fields_by_name['has_tiles'])
_STATUS.fields_by_name['has_tiles'].containing_oneof = _STATUS.oneofs_by_name['has_has_tiles']
_STATUS.oneofs_by_name['has_has_admins'].fields.append(
  _STATUS.fields_by_name['has_admins'])
_STATUS.fields_by_name['has_admins'].containing_oneof = _STATUS.oneofs_by_name['has_has_admins']
_STATUS.oneofs_by_name['has_has_timezones'].fields.append(
  _STATUS.fields_by_name['has_timezones'])
_STATUS.fields_by_name['has_timezones'].containing_oneof = _STATUS.oneofs_by_name['has_has_timezones']
_STATUS.oneofs_by_name['has_has_live_traffic'].fields.append(
  _STATUS.fields_by_name['has_live_traffic'])
_STATUS.fields_by_name['has_live_traffic'].containing_oneof = _STATUS.oneofs_by_name['has_has_live_traffic']
_STATUS.oneofs_by_name['has_bbox'].fields.append(
  _STATUS.fields_by_name['bbox'])
_STATUS.fields_by_name['bbox'].containing_oneof = _STATUS.oneofs_by_name['has_bbox']
_STATUS.oneofs_by_name['has_version'].fields.append(
  _STATUS.fields_by_name['version'])
_STATUS.fields_by_name['version'].containing_oneof = _STATUS.oneofs_by_name['has_version']
_STATUS.oneofs_by_name['has_tileset_last_modified'].fields.append(
  _STATUS.fields_by_name['tileset_last_modified'])
_STATUS.fields_by_name['tileset_last_modified'].containing_oneof = _STATUS.oneofs_by_name['has_tileset_last_modified']
DESCRIPTOR.message_types_by_name['Status'] = _STATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), {
  'DESCRIPTOR' : _STATUS,
  '__module__' : 'status_pb2'
  # @@protoc_insertion_point(class_scope:valhalla.Status)
  })
_sym_db.RegisterMessage(Status)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
